@startuml
component "Client Tools" as client
component "Admin Tools" as admin
!include components/empyrean.puml

package DNS {
!include components/dns.puml
}

package EUARE {
!include components/euare.puml
}

package Walrus as walrus {
!include components/walrus.puml
}

package CLC as clc {
!include components/clc.puml
}

package StorageController as sc {
!include components/sc.puml
}

package VMwareBroker as vb {
!include components/vmwarebroker.puml
}

!ifdef VERBOSE
package Reporting {
  !include components/reporting.puml
}        

package Properties {
    interface "Configuration Management Ops" as propsiface
    wsdispatch --> propsiface
}        
package AdminUI {
!include components/adminui.puml
}
!endif

package CC as cc {
!include components/cc.puml
}
package NC as nc {
!include components/nc.puml
}

clc -down-> cc
clc -right-> sc
clc -left-> walrus

cc -down-> nc

nc .up.> walrus
nc .up.> sc

client --> wsport
admin --> wsport
client ..> dnsport
wsdispatch --> euareiface
wsdispatch --> walruss3ops
wsdispatch --> clcec2
wsdispatch --> sciface
wsdispatch --> vbops
@enduml
